apiVersion: v1
kind: Service
metadata:
  name: controller-service
  namespace: cedanacontroller-system
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
spec:
  selector:
    control-plane: controller-manager
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 1324  # Port on the pod(s)
  type: LoadBalancer
