---
 client:
  process_name: "" 
  dump_frequency_min: 10
  dump_storage_dir: ""
 docker: 
  leave_running: true
 action_scripts: 
  pre_dump: "scripts/pre_dump.sh"
  post_dump: "scripts/post_dump.sh"
  pre_restore: "scripts/pre_restore.sh"
 connection:
  server_addr: "localhost"
  server_port: 5000
