---
 client:
  process_name: "some_process_name" 
  dump_frequency_min: 10
  dump_storage_dir: "/path/to/storage/dir"
 docker: 
  leave_running: true
  dump_storage_dir: "/path/to/storage/dir"
  container_id: ""
 action_scripts: 
  pre_dump: "scripts/pre_dump.sh"
  post_dump: "scripts/post_dump.sh"
  pre_restore: "scripts/pre_restore.sh"
 connection:
  server_addr: "localhost"
  server_port: 5000
 aws: 
  efs_id : "1234567"
  efs_mount_point: "/path/to/efs/mountpoint"