---
 client:
  process_name: "1226634" 
  dump_frequency_min: 10
  dump_storage_dir: "/home/nravichandra/dump_images"
 docker: 
  leave_running: true
  dump_storage_dir: "home/nravichandra/dump_images"
  container_id: ""
 action_scripts: 
  pre_dump: "scripts/pre_dump.sh"
  post_dump: "scripts/post_dump.sh"
  pre_restore: "scripts/pre_restore.sh"
 connection:
  server_addr: "localhost"
  server_port: 5000
