name: Benchmark and Publish 
on: 
  schedule: 
    - cron: '0 0 * * 0'
  workflow_dispatch:

# Cancel any preceding run on the pull request.
concurrency:
  group: docker-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/cedana-dev' }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout cedana
    - uses: actions/checkout@v2
      with:
        ref: fix/iterate-benchmark 
       
    - name: Run Benchmarking Script (${{ matrix.os }})
      run: sudo ./cedana/scripts/ci/benchmark-and-push.sh
      env:
        BIGQUERY_TOKEN: ${{ secrets.BIGQUERY_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
