name: Benchmark and Publish 
on: 
  schedule: 
    - cron: '0 0 * * 0'
  workflow_dispatch:

# Cancel any preceding run on the pull request.
concurrency:
  group: docker-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/cedana-dev' }}

jobs:
  build:
    
    permissions:
      contents: 'read'
      packages: 'read'
      id-token: 'write'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
    - name: Checkout cedana
      uses: actions/checkout@v2
      with:
        ref: fix/iterate-benchmark 

        steps:

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      env: 
        WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_POOL }}
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: 'benchmark-uploader@cedana-benchmarking.iam.gserviceaccount.com'

    - name: Run Benchmarking Script (${{ matrix.os }})
      run: sudo -E make -C scripts/ci benchmarking
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
